#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# GoAds — Prebid Server Installer
# Repo: https://github.com/nufieold-beep/goads
#
# Supported: Ubuntu 20.04 / 22.04 / 24.04, Debian 11/12
# Run as root or with sudo:
#   curl -fsSL https://raw.githubusercontent.com/nufieold-beep/goads/main/install.sh | bash
#   — or —
#   bash install.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Constants ─────────────────────────────────────────────────────────────────
GO_VERSION="1.24.0"
INSTALL_DIR="/opt/prebid-server"
SERVICE_NAME="prebid-server"
BINARY_NAME="prebid-server"
REPO_URL="https://github.com/nufieold-beep/goads.git"
GO_TARBALL="go${GO_VERSION}.linux-amd64.tar.gz"
GO_URL="https://dl.google.com/go/${GO_TARBALL}"

# ── Root check ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  error "Please run this script as root or with sudo."
fi

# ── Detect public IP for default external_url ────────────────────────────────
PUBLIC_IP=$(curl -sf --max-time 5 https://api.ipify.org || hostname -I | awk '{print $1}')

# ── Interactive config ────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   GoAds Prebid Server — Interactive Installer"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

read -rp "External URL / public IP  [${PUBLIC_IP}]: " EXT_URL
EXT_URL="${EXT_URL:-${PUBLIC_IP}}"
# Prepend http:// if no scheme given
[[ "$EXT_URL" =~ ^https?:// ]] || EXT_URL="http://${EXT_URL}"

read -rp "Listen port               [80]: "    PORT;      PORT="${PORT:-80}"
read -rp "Admin port                [6060]: "  ADMIN_PORT; ADMIN_PORT="${ADMIN_PORT:-6060}"
read -rp "GDPR default (0=off,1=on) [0]: "     GDPR;      GDPR="${GDPR:-0}"
read -rp "Dashboard admin password  [admin]: " DASH_PASS;  DASH_PASS="${DASH_PASS:-admin}"

echo ""
info "Configuration:"
info "  external_url : ${EXT_URL}"
info "  port         : ${PORT}"
info "  admin_port   : ${ADMIN_PORT}"
info "  gdpr default : ${GDPR}"
echo ""

# ── Step 1: System packages ───────────────────────────────────────────────────
info "Installing system packages…"
apt-get update -qq
apt-get install -y --no-install-recommends \
  wget curl git gcc build-essential ca-certificates \
  libatomic1 2>/dev/null || true

# ── Step 2: Install Go ────────────────────────────────────────────────────────
if go version 2>/dev/null | grep -q "go${GO_VERSION}"; then
  info "Go ${GO_VERSION} already installed — skipping."
else
  info "Downloading Go ${GO_VERSION}…"
  wget -q "${GO_URL}" -O "/tmp/${GO_TARBALL}"
  rm -rf /usr/local/go
  tar -C /usr/local -xf "/tmp/${GO_TARBALL}"
  rm "/tmp/${GO_TARBALL}"
  info "Go ${GO_VERSION} installed to /usr/local/go"
fi

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH
export GOPROXY="https://proxy.golang.org"

go version || error "Go installation failed."

# ── Step 3: Clone / update repo ───────────────────────────────────────────────
BUILD_DIR="/tmp/goads-build"
if [[ -d "${BUILD_DIR}/.git" ]]; then
  info "Updating existing clone…"
  git -C "${BUILD_DIR}" pull --ff-only
else
  info "Cloning ${REPO_URL}…"
  git clone --depth=1 "${REPO_URL}" "${BUILD_DIR}"
fi

cd "${BUILD_DIR}"

# ── Step 4: Build ─────────────────────────────────────────────────────────────
info "Fetching Go modules…"
go mod tidy
go mod vendor

info "Building binary…"
CGO_ENABLED=1 go build -mod=vendor -o "${BINARY_NAME}" .
info "Build complete: $(du -sh ${BINARY_NAME} | cut -f1) binary."

# ── Step 5: Install binary and static assets ─────────────────────────────────
info "Installing to ${INSTALL_DIR}…"
mkdir -p "${INSTALL_DIR}"
install -m 0755 "${BINARY_NAME}" "${INSTALL_DIR}/${BINARY_NAME}"
cp -r static "${INSTALL_DIR}/static"
cp -r stored_requests "${INSTALL_DIR}/stored_requests"
cp -r stored_responses "${INSTALL_DIR}/stored_responses" 2>/dev/null || true

# ── Step 6: Write pbs.yaml (only if not already present) ─────────────────────
PBS_YAML="${INSTALL_DIR}/pbs.yaml"
if [[ -f "${PBS_YAML}" ]]; then
  warn "pbs.yaml already exists — skipping config generation."
  warn "Edit ${PBS_YAML} manually if needed."
else
  info "Writing ${PBS_YAML}…"
  cat > "${PBS_YAML}" <<EOF
# GoAds Prebid Server — main configuration
# Generated by install.sh on $(date --iso-8601=seconds)

port: ${PORT}
admin_port: ${ADMIN_PORT}

external_url: "${EXT_URL}"

status_response: "ok"

gdpr:
  default_value: "${GDPR}"

stored_requests:
  filesystem:
    enabled: true
    directorypath: ./stored_requests/data/by_id

stored_responses:
  filesystem:
    enabled: true
    directorypath: ./stored_responses/data/by_id

auction_timeouts_ms:
  default: 800
  max: 1500

tmax_adjustments:
  enabled: true
  bidder_network_latency_buffer_ms: 15
  pbs_response_preparation_duration_ms: 15
  bidder_response_duration_min_ms: 50

http_client:
  max_idle_connections: 5000
  max_idle_connections_per_host: 500
  max_connections_per_host: 0
  idle_connection_timeout_seconds: 30

compression:
  response:
    enable_gzip: true
EOF
fi

# ── Step 7: systemd service unit ─────────────────────────────────────────────
UNIT_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
if [[ -f "${UNIT_FILE}" ]]; then
  warn "systemd unit already exists — updating ExecStart only."
fi

cat > "${UNIT_FILE}" <<EOF
[Unit]
Description=GoAds Prebid Server
After=network.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_DIR}
ExecStart=${INSTALL_DIR}/${BINARY_NAME}
Environment=DASH_ADMIN_PASS=${DASH_PASS}
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

# ── Step 8: Enable and (re)start service ─────────────────────────────────────
info "Enabling and starting ${SERVICE_NAME}…"
systemctl daemon-reload
systemctl enable "${SERVICE_NAME}"
systemctl restart "${SERVICE_NAME}"
sleep 2

if systemctl is-active --quiet "${SERVICE_NAME}"; then
  info "Service is running."
else
  warn "Service failed to start. Check logs with:"
  warn "  journalctl -u ${SERVICE_NAME} -n 50 --no-pager"
  exit 1
fi

# ── Step 9: Firewall (ufw — optional) ─────────────────────────────────────────
if command -v ufw &>/dev/null && ufw status | grep -q "Status: active"; then
  info "Opening ports ${PORT} and ${ADMIN_PORT} in ufw…"
  ufw allow "${PORT}/tcp"   comment 'GoAds main port'   2>/dev/null || true
  ufw allow "${ADMIN_PORT}/tcp" comment 'GoAds admin'   2>/dev/null || true
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}  Installation complete!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Health check : curl ${EXT_URL}/status"
echo "  Dashboard    : ${EXT_URL}/dashboard"
echo "  Admin        : ${EXT_URL%:*}:${ADMIN_PORT}/metrics"
echo ""
echo "  Config file  : ${PBS_YAML}"
echo "  Binary       : ${INSTALL_DIR}/${BINARY_NAME}"
echo ""
echo "  Manage service:"
echo "    systemctl status  ${SERVICE_NAME}"
echo "    systemctl restart ${SERVICE_NAME}"
echo "    journalctl -u ${SERVICE_NAME} -f"
echo ""
